### ISSUE TITLE
Cant send commands

### ISSUE THREAD

**Issue by RonDeppe** [suborb/philips_android_tv#42]
Hello,
Sorry for asking my question here but I don't know where else to ask.
How do I send any command to the tv?
When I use "http://{My-IP}:1925/system" I get a response, but when I try to run any of the other commands they don't work.
I hoped this would help me, but I don't know how to use the username and password to send working commands.
Could someone please give me an example?
Thank you.

For extra information I have a 32PFS6401/12 with android tv.

**Comment by ThreeCO** [comment]
Did you do the pairing according to the readme? In that step you will receive user and password

**Comment by RonDeppe** [comment]
Yes, I did receive my username and password but I don't understand how I could use those to for example turn on the tv. Thanks for the quick reply.

**Comment by ThreeCO** [comment]
You are welcome 😀
In general you can use GET and POST to READ and WRITE certain information. 

If you want to change settings you will need to POST the necessary information json encoded to your tv. 

Just have a look at the python script in this repository. Actually it describes quite literally what it does 😅

btw. turning the TV on is one of the more complex tasks since mostly WiFi is disabled when it is in standby. So you would first try to wake it up by sending WOL packets. I never managed that though. 

It's way more easy to select a different channel or change volume.

**Comment by RonDeppe** [comment]
Thanks for the help,
When I try to for example use "get_volume" I get the error:
"The server understood the request, but is refusing to fulfill it".
Do you know how to fix this?

**Comment by RonDeppe** [comment]
Fixed
